### ISSUE TITLE
Replace pycrypto with pycryptodome

### ISSUE THREAD

**Issue by chromatic** [nformant1/bip38#1]
I played with trying to build this on Windows, and I ran into `pycrypto` compilation errors. Looks like the former has been unmaintained for a while, with a recommendation to migrate to the latter instead.

**Comment by nformant1** [comment]
The issue should be resolved with the latest PR, feel free to let me know if this issue can be closed

**Comment by chromatic** [comment]
I think so.

I set up a [Python Windows installer at ActiveState](https://platform.activestate.com/dogecoin/bip38-paper-wallet/distributions). If this works for Windows users to download and install Python and run this program, I can enhance it further.
